// <auto-generated />
using BaliTreeData;
using BaliTreeData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BaliTree.Migrations
{
    [DbContext(typeof(BaliTreeContext))]
    [Migration("20171228203156_architecturechange")]
    partial class architecturechange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaliTreeData.Models.StockEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Change");

                    b.Property<DateTime>("Date");

                    b.Property<int>("EventType");

                    b.Property<int>("StockItemId");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId");

                    b.ToTable("StockEvent");
                });

            modelBuilder.Entity("BaliTreeData.Models.StockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AmountPaid");

                    b.Property<int>("CurrentStock");

                    b.Property<string>("ItemName");

                    b.Property<int?>("OrderId");

                    b.Property<decimal>("RRP");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("BaliTreeData.Models.StockOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BaliTreeData.Models.StockEvent", b =>
                {
                    b.HasOne("BaliTreeData.Models.StockItem")
                        .WithMany("StockEvent")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BaliTreeData.Models.StockItem", b =>
                {
                    b.HasOne("BaliTreeData.Models.StockOrder", "Order")
                        .WithMany("StockItem")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
